[accounts.sanch]
default = true
email = "email1@domain.com"
display-name = ""
downloads-dir = "/home/adrian/Downloads"

[accounts.sanch.backend]
type = "imap"
host = "imap.gmail.com"
port = 993
login = "email1@domain.com"

[accounts.sanch.backend.encryption]
type = "tls"

[accounts.sanch.backend.auth]
type = "password"
command = "pass show email/sanch/app_pass"

[accounts.sanch.message.send.backend]
type = "smtp"
host = "smtp.gmail.com"
port = 587
login = "email1@domain.com"

[accounts.sanch.message.send.backend.encryption]
type = "start-tls"

[accounts.sanch.message.send.backend.auth]
type = "password"
command = "pass show email/sanch/app_pass"

[accounts.leet]
default = false
email = "email2@domain.com"
display-name = "Leetius Leetington"
downloads-dir = "/home/adrian/Downloads"

[accounts.leet.backend]
type = "imap"
host = "imap.gmail.com"
port = 993
login = "email2@domain.com"

[accounts.leet.backend.encryption]
type = "tls"

[accounts.leet.backend.auth]
type = "password"
command = "pass show email/leet/app_pass"

[accounts.leet.message.send.backend]
type = "smtp"
host = "smtp.gmail.com"
port = 587
login = "email2@domain.com"

[accounts.leet.message.send.backend.encryption]
type = "start-tls"

[accounts.leet.message.send.backend.auth]
type = "password"
command = "pass show email/leet/app_pass"

[accounts.spag]
default = false
email = "email3@domain.com"
display-name = "Cryptic Spag"
downloads-dir = "/home/adrian/Downloads"

[accounts.spag.backend]
type = "imap"
host = "imap.gmail.com"
port = 993
login = "email3@domain.com"

[accounts.spag.backend.encryption]
type = "tls"

[accounts.spag.backend.auth]
type = "password"
command = "pass show email/spag/app_pass"

[accounts.spag.message.send.backend]
type = "smtp"
host = "smtp.gmail.com"
port = 587
login = "email3@domain.com"

[accounts.spag.message.send.backend.encryption]
type = "start-tls"

[accounts.spag.message.send.backend.auth]
type = "password"
command = "pass show email/spag/app_pass"

[accounts.sbc]
default = false
email = "email4@domain.com"
display-name = "Adrian Sanchez"
downloads-dir = "/home/adrian/Downloads"

[accounts.sbc.backend]
type = "imap"
host = "imap.mail.att.net"
port = 993
login = "email4@domain.com"

[accounts.sbc.backend.encryption]
type = "tls"

[accounts.sbc.backend.auth]
type = "password"
command = "pass show email/sbc/app_pass"

[accounts.sbc.message.send.backend]
type = "smtp"
host = "smtp.mail.att.net"
port = 587
login = "email4@domain.com"

[accounts.sbc.message.send.backend.encryption]
type = "start-tls"

[accounts.sbc.message.send.backend.auth]
type = "password"
command = "pass show email/sbc/app_pass"
