[accounts.sanch]
default = true
email = "email1@domain.com"
display-name = "Adrian Sanchez"
signature = "V/r,\n"
signature-delim = "--\n"
downloads-dir = "~/Downloads"
folder.aliases.inbox = "INBOX"
folder.aliases.all = "[Gmail]/All Mail"
folder.aliases.drafts = "[Gmail]/Drafts"
folder.aliases.important = "[Gmail]/Important"
folder.aliases.sent = "[Gmail]/Sent Mail"
folder.aliases.spam = "[Gmail]/Spam"
folder.aliases.starred = "[Gmail]/Starred"
folder.aliases.trash = "[Gmail]/Trash"
folder.list.page-size = 25
envelope.list.page-size = 20
backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.login = "email1@domain.com"
backend.encryption.type = "tls"
backend.auth.type = "password"
backend.auth.command = "pass show email/email1/app_pass"
message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 587
message.send.backend.login = "email1@domain.com"
message.send.backend.encryption.type = "start-tls"
message.send.backend.auth.type = "password"
message.send.backend.auth.command = "pass show email/email1/app_pass"

[accounts.leet]
default = true
email = "email2@domain.com"
display-name = "Leetius Leetington"
signature = "V/r,\n"
signature-delim = "--\n"
downloads-dir = "~/Downloads"
folder.aliases.inbox = "INBOX"
folder.aliases.all = "[Gmail]/All Mail"
folder.aliases.drafts = "[Gmail]/Drafts"
folder.aliases.important = "[Gmail]/Important"
folder.aliases.sent = "[Gmail]/Sent Mail"
folder.aliases.spam = "[Gmail]/Spam"
folder.aliases.starred = "[Gmail]/Starred"
folder.aliases.trash = "[Gmail]/Trash"
folder.list.page-size = 25
envelope.list.page-size = 15
backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.login = "email2@domain.com"
backend.encryption.type = "tls"
backend.auth.type = "password"
backend.auth.command = "pass show email/email2/app_pass"
message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 587
message.send.backend.login = "email2@domain.com"
message.send.backend.encryption.type = "start-tls"
message.send.backend.auth.type = "password"
message.send.backend.auth.command = "pass show email/email2/app_pass"

[accounts.spag]
default = true
email = "email3@domain.com"
display-name = "Cryptic Spag"
signature = "V/r,\n"
signature-delim = "--\n"
downloads-dir = "~/Downloads"
folder.aliases.inbox = "INBOX"
folder.aliases.all = "[Gmail]/All Mail"
folder.aliases.drafts = "[Gmail]/Drafts"
folder.aliases.important = "[Gmail]/Important"
folder.aliases.sent = "[Gmail]/Sent Mail"
folder.aliases.spam = "[Gmail]/Spam"
folder.aliases.starred = "[Gmail]/Starred"
folder.aliases.trash = "[Gmail]/Trash"
folder.list.page-size = 25
envelope.list.page-size = 10
backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.login = "email3@domain.com"
backend.encryption.type = "tls"
backend.auth.type = "password"
backend.auth.command = "pass show email/email3/app_pass"
message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 587
message.send.backend.login = "email3@domain.com"
message.send.backend.encryption.type = "start-tls"
message.send.backend.auth.type = "password"
message.send.backend.auth.command = "pass show email/email3/app_pass"

[accounts.sbc]
default = true
email = "email4@domain.com"
display-name = "Adrian Sanchez"
signature = "V/r,\n"
signature-delim = "--\n"
downloads-dir = "~/Downloads"
folder.aliases.inbox = "INBOX"
folder.aliases.archive = "Archive"
folder.aliases.bulk = "Bulk"
folder.aliases.drafts = "Draft"
folder.aliases.sent = "Sent"
folder.aliases.trash = "Trash"
folder.list.page-size = 25
envelope.list.page-size = 25
backend.type = "imap"
backend.host = "imap.mail.att.net"
backend.port = 993
backend.login = "email4@domain.com"
backend.encryption.type = "tls"
backend.auth.type = "password"
backend.auth.command = "pass show email/email4/app_pass"
message.send.backend.type = "smtp"
message.send.backend.host = "smtp.mail.att.net"
message.send.backend.port = 587
message.send.backend.login = "email4@domain.com"
message.send.backend.encryption.type = "start-tls"
message.send.backend.auth.type = "password"
message.send.backend.auth.command = "pass show email/email4/app_pass"
