signature = "V/r,\n"
signature-delim = "-- \n"
downloads-dir = "~/Downloads"

[accounts.sanch]
default = true
email = "email1@domain.com"
display-name = "Adrian Sanchez"
downloads-dir = "~/Downloads"
folder.aliases.inbox = "INBOX"
folder.aliases.sent = "Sent"
folder.aliases.drafts = "Drafts"
folder.aliases.trash = "Trash"
folder.aliases.starred = "Starred"
folder.list.page-size = 25
envelope.list.page-size = 25
backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.login = "email1@domain.com"
backend.encryption.type = "tls"
backend.auth.type = "password"
backend.auth.command = "pass show email/email1/app_pass"
message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 587
message.send.backend.login = "email1@domain.com"
message.send.backend.encryption.type = "start-tls"
message.send.backend.auth.type = "password"
message.send.backend.auth.command = "pass show email/email1/app_pass"

[accounts.leet]
default = false
email = "email2@domain.com"
display-name = "Leetius Leetington"
downloads-dir = "~/Downloads"
folder.aliases.inbox = "INBOX"
folder.aliases.sent = "Sent"
folder.aliases.drafts = "Drafts"
folder.aliases.trash = "Trash"
folder.aliases.starred = "Starred"
folder.list.page-size = 25
envelope.list.page-size = 25
backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.login = "email2@domain.com"
backend.encryption.type = "tls"
backend.auth.type = "password"
backend.auth.command = "pass show email/email2/app_pass"
message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 587
message.send.backend.login = "email2@domain.com"
message.send.backend.encryption.type = "start-tls"
message.send.backend.auth.type = "password"
message.send.backend.auth.command = "pass show email/email2/app_pass"

[accounts.crypt]
default = false
email = "email3@domain.com"
display-name = "Cryptic Spag"
downloads-dir = "~/Downloads"
folder.aliases.inbox = "INBOX"
folder.aliases.sent = "Sent"
folder.aliases.drafts = "Drafts"
folder.aliases.trash = "Trash"
folder.aliases.starred = "Starred"
folder.list.page-size = 25
envelope.list.page-size = 25
backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.login = "email3@domain.com"
backend.encryption.type = "tls"
backend.auth.type = "password"
backend.auth.command = "pass show email/email3/app_pass"
message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 587
message.send.backend.login = "email3@domain.com"
message.send.backend.encryption.type = "start-tls"
message.send.backend.auth.type = "password"
message.send.backend.auth.command = "pass show email/email3/app_pass"
