configurations:
    -
        host: imap.gmail.com
        port: 993
        tls: true
        tlsOptions:
            rejectUnauthorized: true
            starttls: false
        usernameCMD: "pass google/leet/username"
        passwordCMD: "pass google/leet/app_pass"
        boxes:
            -
                mailbox: INBOX
                onNewMail: "mbsync 'leet:INBOX' && notmuch new"
                onDeletedMail: "mbsync 'leet:INBOX' && notmuch new"
                onNewMailPost: "notify-send --icon='/home/adrian/Pictures/icons/neomutt.png' 'youhavemail: leet' 'New message(s) for leet in INBOX.'"
                onDeletedMailPost: SKIP
            -
                mailbox: "[Gmail]/All Mail"
                onNewMail: "mbsync 'leet:[Gmail]/All Mail' && notmuch new"
                onDeletedMail: "mbsync 'leet:[Gmail]/All Mail' && notmuch new"
                onNewMailPost: SKIP
                onDeletedMailPost: SKIP
            -
                mailbox: "[Gmail]/Drafts"
                onNewMail: "mbsync 'leet:[Gmail]/Drafts' && notmuch new"
                onDeletedMail: "mbsync 'leet:[Gmail]/Drafts' && notmuch new"
                onNewMailPost: SKIP
                onDeletedMailPost: SKIP
            -
                mailbox: "[Gmail]/Sent Mail"
                onNewMail: "mbsync 'leet:[Gmail]/Sent Mail' && notmuch new"
                onDeletedMail: "mbsync 'leet:[Gmail]/Sent Mail' && notmuch new"
                onNewMailPost: SKIP
                onDeletedMailPost: SKIP
            -
                mailbox: "[Gmail]/Trash"
                onNewMail: "mbsync 'leet:[Gmail]/Trash' && notmuch new"
                onDeletedMail: "mbsync 'leet:[Gmail]/Trash' && notmuch new"
                onNewMailPost: SKIP
                onDeletedMailPost: SKIP
            -
                mailbox: "[Gmail]/Starred"
                onNewMail: "mbsync 'leet:[Gmail]/Starred' && notmuch new"
                onDeletedMail: "mbsync 'leet:[Gmail]/Starred' && notmuch new"
                onNewMailPost: SKIP
                onDeletedMailPost: SKIP
            -
                mailbox: "[Gmail]/Spam"
                onNewMail: "mbsync 'leet:[Gmail]/Spam' && notmuch new"
                onDeletedMail: "mbsync 'leet:[Gmail]/Spam' && notmuch new"
                onNewMailPost: SKIP
                onDeletedMailPost: SKIP
            -
                mailbox: Archive
                onNewMail: "mbsync 'leet:Archive' && notmuch new"
                onDeletedMail: "mbsync 'leet:Archive' && notmuch new"
                onNewMailPost: SKIP
                onDeletedMailPost: SKIP
