configurations:
    -
        host: imap.gmail.com
        port: 993
        tls: true
        tlsOptions:
            rejectUnauthorized: true
            starttls: false
        usernameCMD: "pass google/spag/username"
        passwordCMD: "pass google/spag/app_pass"
        boxes:
            -
                mailbox: INBOX
                onNewMail: "mbsync 'spag:INBOX' && notmuch new"
                onDeletedMail: "mbsync 'spag:INBOX' && notmuch new"
                onNewMailPost: SKIP
                onDeletedMailPost: SKIP
            -
                mailbox: "[Gmail]/All Mail"
                onNewMail: "mbsync 'spag:[Gmail]/All Mail' && notmuch new"
                onDeletedMail: "mbsync 'spag:[Gmail]/All Mail' && notmuch new"
                onNewMailPost: SKIP
                onDeletedMailPost: SKIP
            -
                mailbox: "[Gmail]/Drafts"
                onNewMail: "mbsync 'spag:[Gmail]/Drafts' && notmuch new"
                onDeletedMail: "mbsync 'spag:[Gmail]/Drafts' && notmuch new"
                onNewMailPost: SKIP
                onDeletedMailPost: SKIP
            -
                mailbox: "[Gmail]/Sent Mail"
                onNewMail: "mbsync 'spag:[Gmail]/Sent Mail' && notmuch new"
                onDeletedMail: "mbsync 'spag:[Gmail]/Sent Mail' && notmuch new"
                onNewMailPost: SKIP
                onDeletedMailPost: SKIP
            -
                mailbox: "[Gmail]/Trash"
                onNewMail: "mbsync 'spag:[Gmail]/Trash' && notmuch new"
                onDeletedMail: "mbsync 'spag:[Gmail]/Trash' && notmuch new"
                onNewMailPost: SKIP
                onDeletedMailPost: SKIP
            -
                mailbox: "[Gmail]/Starred"
                onNewMail: "mbsync 'spag:[Gmail]/Starred' && notmuch new"
                onDeletedMail: "mbsync 'spag:[Gmail]/Starred' && notmuch new"
                onNewMailPost: SKIP
                onDeletedMailPost: SKIP
            -
                mailbox: "[Gmail]/Spam"
                onNewMail: "mbsync 'spag:[Gmail]/Spam' && notmuch new"
                onDeletedMail: "mbsync 'spag:[Gmail]/Spam' && notmuch new"
                onNewMailPost: SKIP
                onDeletedMailPost: SKIP
            -
                mailbox: Archive
                onNewMail: "mbsync 'spag:Archive' && notmuch new"
                onDeletedMail: "mbsync 'spag:Archive' && notmuch new"
                onNewMailPost: SKIP
                onDeletedMailPost: SKIP
