configurations:
    -
        host: imap.gmail.com
        port: 993
        tls: true
        tlsOptions:
            rejectUnauthorized: true
        usernameCMD: "pass google/leet/username"
        passwordCMD: "pass google/leet/app_pass"
        boxes:
            -
                mailbox: INBOX
                onNewMail: "mbsync 'leet:INBOX'"
                onNewMailPost: "notify-send --icon='/home/adrian/Pictures/icons/neomutt.png' 'youhavemail: leet' 'New message(s) for leet in INBOX.'"
            -
                mailbox: "[Gmail]/Drafts"
                onNewMail: "mbsync 'leet:[Gmail]/Drafts'"
                onNewMailPost: SKIPPED
            -
                mailbox: "[Gmail]/Sent Mail"
                onNewMail: "mbsync 'leet:[Gmail]/Sent Mail'"
                onNewMailPost: SKIPPED
            -
                mailbox: "[Gmail]/Trash"
                onNewMail: "mbsync 'leet:[Gmail]/Trash'"
                onNewMailPost: SKIPPED
            -
                mailbox: "[Gmail]/Starred"
                onNewMail: "mbsync 'leet:[Gmail]/Starred'"
                onNewMailPost: SKIPPED
            -
                mailbox: "[Gmail]/Spam"
                onNewMail: "mbsync 'leet:[Gmail]/Spam'"
                onNewMailPost: SKIPPED
            -
                mailbox: Archive
                onNewMail: "mbsync 'leet:Archive'"
                onNewMailPost: SKIPPED
