configurations:
    -
        host: imap.mail.att.net
        port: 993
        tls: true
        tlsOptions:
            rejectUnauthorized: true
        usernameCMD: "pass yahoo/sbc/username"
        passwordCMD: "pass yahoo/sbc/app_pass"
        boxes:
            -
                mailbox: INBOX
                onNewMail: "mbsync 'sbc:INBOX'"
                onNewMailPost: "notify-send --icon='/home/adrian/Pictures/icons/neomutt.png' 'youhavemail: sbc' 'New message(s) for sbc in INBOX'"
            -
                mailbox: "Draft"
                onNewMail: "mbsync 'sbc:Draft'"
                onNewMailPost: SKIPPED
            -
                mailbox: "Sent"
                onNewMail: "mbsync 'sbc:Sent'"
                onNewMailPost: SKIPPED
            -
                mailbox: "Trash"
                onNewMail: "mbsync 'sbc:Trash'"
                onNewMailPost: SKIPPED
            -
                mailbox: "Starred"
                onNewMail: "mbsync 'sbc:Starred'"
                onNewMailPost: SKIPPED
            -
                mailbox: "Bulk"
                onNewMail: "mbsync 'sbc:Bulk'"
                onNewMailPost: SKIPPED
            -
                mailbox: Archive
                onNewMail: "mbsync 'sbc:Archive'"
                onNewMailPost: SKIPPED
