configurations:
    -
        host: imap.gmail.com
        port: 993
        tls: true
        tlsOptions:
            rejectUnauthorized: true
        usernameCMD: "pass google/spag/username"
        passwordCMD: "pass google/spag/app_pass"
        boxes:
            -
                mailbox: INBOX
                onNewMail: "mbsync 'spag:INBOX'"
                onNewMailPost: "notify-send --icon='/home/adrian/Pictures/icons/neomutt.png' 'youhavemail: spag' 'New messages for spag in INBOX."
            -
                mailbox: "[Gmail]/Drafts"
                onNewMail: "mbsync 'spag:[Gmail]/Drafts'"
                onNewMailPost: "notify-send --icon='/home/adrian/Pictures/icons/neomutt.png' 'youhavemail: spag' 'New messages for spag in [Gmail]/Drafts."
            -
                mailbox: "[Gmail]/Sent Mail"
                onNewMail: "mbsync 'spag:[Gmail]/Sent Mail'"
                onNewMailPost: "notify-send --icon='/home/adrian/Pictures/icons/neomutt.png' 'youhavemail: spag' 'New messages for spag in [Gmail]/Sent Mail."
            -
                mailbox: "[Gmail]/Trash"
                onNewMail: "mbsync 'spag:[Gmail]/Trash'"
                onNewMailPost: "notify-send --icon='/home/adrian/Pictures/icons/neomutt.png' 'youhavemail: spag' 'New messages for spag in [Gmail]/Trash."
            -
                mailbox: "[Gmail]/Starred"
                onNewMail: "mbsync 'spag:[Gmail]/Starred'"
                onNewMailPost: "notify-send --icon='/home/adrian/Pictures/icons/neomutt.png' 'youhavemail: spag' 'New messages for spag in [Gmail]/Starred."
            -
                mailbox: "[Gmail]/Spam"
                onNewMail: "mbsync 'spag:[Gmail]/Spam'"
                onNewMailPost: "notify-send --icon='/home/adrian/Pictures/icons/neomutt.png' 'youhavemail: spag' 'New messages for spag in [Gmail]/Spam."
            -
                mailbox: Archive
                onNewMail: "mbsync 'spag:Archive'"
                onNewMailPost: "notify-send --icon='/home/adrian/Pictures/icons/neomutt.png' 'youhavemail: spag' 'New messages for spag in Archive."
